
name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12.2
      - name: List build directory
        run: ls -R ./docs/build
      - name: Create .nojekyll
        run: touch ./docs/build/.nojekyll
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme numpy
      - name: List installed packages
        run: |
          pip list
      - name: Sphinx Build
        run: |
          sphinx-build -b html ./docs/source ./docs/build


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          force_orphan: true
